<?xml version="1.0" encoding="UTF-8"?>
<!-- 
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements. See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership. Sveriges Kommuner och Landsting licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License. You may obtain a copy of the License at
 
 http://www.apache.org/licenses/LICENSE-2.0
 
 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
 -->
<wsdl:definitions name="HamtaSocialforsakringsformanerInteraction"
    targetNamespace="urn:shs:skl:ekonomisktbistand:HamtaSocialforsakringsformaner:1:shsbp10" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns:tns="urn:shs:skl:ekonomisktbistand:HamtaSocialforsakringsformaner:1:shsbp10"
    xmlns:sr="urn:shs:skl:ekonomisktbistand:HamtaSocialforsakringsformanerResponder:1">
    
    <wsdl:documentation>
        Tjänsteinteraktionens namn:
            HamtaSocialforsakringsformanerInteraction
        Beskrivning: 
            Hämtar socialförskringsersättningar från försäkringskassan
        Revisioner: 
            2013-03-11: Utkast 1.0 RC1, peter.larsson@callistaenterprise.se
            2013-04-20: Utkast 1.0 RC2, peter.larsson@callistaenterprise.se
        Tjänstedomän: 
            eif:ekonomisktbistand
        Tjänsteinteraktionstyp: 
            Fråga-svar
            SHS Version 2.0 SOAP-based Protocol, SHSBP10
        Förvaltning: 
            TBD
    </wsdl:documentation>
    
    <wsdl:types>
        <xs:schema>
            <xs:import schemaLocation="HamtaSocialforsakringsformanerResponder_1.0.xsd" namespace="urn:shs:skl:ekonomisktbistand:HamtaSocialforsakringsformanerResponder:1" />
        </xs:schema>
    </wsdl:types>
    
    <wsdl:message name="HamtaSocialforsakringsformanerRequest">
        <wsdl:part name="request" element="sr:HamtaSocialforsakringsformaner" />
    </wsdl:message>
    
    <wsdl:message name="HamtaSocialforsakringsformanerResponse">
        <wsdl:part name="response" element="sr:HamtaSocialforsakringsformanerResponse" />
    </wsdl:message>
    
    <wsdl:portType name="HamtaSocialforsakringsformanerResponderInterface">
        <wsdl:operation name="HamtaSocialforsakringsformaner">
            <wsdl:input message="tns:HamtaSocialforsakringsformanerRequest" />
            <wsdl:output message="tns:HamtaSocialforsakringsformanerResponse" />
        </wsdl:operation>
    </wsdl:portType>
    
    <wsdl:binding name="HamtaSocialforsakringsformanerResponderBinding" type="tns:HamtaSocialforsakringsformanerResponderInterface">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="HamtaSocialforsakringsformaner">
            <soap:operation soapAction="urn:shs:skl:ekonomisktbistand:HamtaSocialforsakringsformanerResponder:1:HamtaSocialforsakringsformaner" style="document" />
            <wsdl:input>
                <soap:body use="literal" parts="request" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:service name="HamtaSocialforsakringsformanerResponderService">
        <wsdl:port name="HamtaSocialforsakringsformanerResponderPort" binding="tns:HamtaSocialforsakringsformanerResponderBinding">
            <soap:address location="http://tempuri.org"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
